-- database: :memory:
CREATE TABLE families (
  family_id          NUMBER GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1000 INCREMENT BY 1 CACHE 50)  -- begins at 1000
    PRIMARY KEY,
  parish_member      CHAR(1)  DEFAULT 'N' NOT NULL CHECK (parish_member IN ('Y','N')),
  parish_number      VARCHAR2(40)  UNIQUE,
  street             VARCHAR2(50) NOT NULL,
  city               VARCHAR2(30)  NOT NULL,
  state              VARCHAR2(2)  NOT NULL,
  zip                VARCHAR2(10)  NOT NULL,
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE contacts (
  contact_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id    NUMBER NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  lastname     VARCHAR2(30) NOT NULL,
  firstname    VARCHAR2(30) NOT NULL,
  middle       VARCHAR2(30),
  relationship VARCHAR2(20)  NOT NULL CHECK (relationship IN ('FATHER','MOTHER', 'GUARDIAN','UNCLE','AUNT', 'GRANDPARENT','BROTHER','SISTER','COUSIN')),
  phone        VARCHAR2(15),
  email        VARCHAR2(80),
  is_emergency CHAR(1)      DEFAULT 'N' NOT NULL CHECK (is_emergency IN ('Y','N'))
);

CREATE INDEX ix_contacts_family ON contacts(family_id, lastname, firstname);
CREATE INDEX ix_contacts_phone  ON contacts(family_id, phone);
CREATE INDEX ix_contacts_email  ON contacts(family_id, email);

CREATE TABLE children (
  child_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id          NUMBER NOT NULL REFERENCES families(family_id) ON DELETE CASCADE,
  lastname           VARCHAR2(30) NOT NULL,
  firstname          VARCHAR2(30) NOT NULL,
  middle             VARCHAR2(30),
  saintname          VARCHAR2(30),
  dob                DATE NOT NULL,
  child_allergies    VARCHAR2(200),
  is_name_exception  CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_name_exception IN ('Y','N')),
  exception_notes    VARCHAR2(500)
);
CREATE INDEX ix_children_family ON children(family_id, lastname, firstname, saintname, dob);
